import forest_cover_change_detection.models.attention.dot_score
import forest_cover_change_detection.models.attention.general_score
import forest_cover_change_detection.models.attention.addative_score
import forest_cover_change_detection.models.attention.simple_score
from .feature_extractor import FeatureExtractor
from .combiner import Combiner
